# Site settings
baseurl = "http://xebuz.github.io/blog/"
languageCode = "en-us"
title = "xeBuz personal blog"
theme = "hugo-cactus-theme"

config = "config.toml"
canonifyurls = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
    name = "xeBuz"
    description = "Personal Website"
    bio = "Developer - Programmer - Gopher"

    # Enter optionally your twitter account
    twitter = "xeBuz"
    # Disable comments by leaving disqusShortname empty
    # disqusShortname = "spf13"
    # # Enter your tracking code to enable Google Analytics
    googleAnalytics = ""
    enableRSS = true

    # The variables below are optionally too and can be used to
    # translate or customize each string of the theme.

    # Navigation links
    home = ""
    about = ""
    subscribe = ""
    # Pagination links
    olderPosts = ""
    newerPosts = ""
    readMore = ""
    copyright = ""
    # Sharing options and author information in posts
    aboutAuthor = "lalalala"
    tweet = ""
    share = ""
    # 404 page
    title404 = ""
    subtitle404 = ""